name: Build candidate
on:
  push:
    branches: [main]
  workflow_dispatch:
permissions:
  contents: read
  id-token: write
jobs:
  candidate:
    uses: ntanis-dev/ci/.github/workflows/project-candidate.yml@4f1322ca2d750f31d3b0436a92a2bea0306e2527
    with:
      project: terminal-slot
      build-matrix: >-
        [{"os":"ubuntu-latest","script":"release:build","artifactDirectory":"ntanis-release","includeExtensions":"tgz","includeFiles":"*.tgz","platform":"source","architecture":"any","platformSigned":false,"install":false}]
